---
title: "Cosinor_Quarto"
format: 
  docx:
    toc: true
    number-sections: true
    highlight-style: github
editor: visual
---

## Cosinar

This document goes through tutorials for the cosinor function of the psych package.

## Setting up Data

This part will load the libraries

```{r load-libraries}

#| echo: false

library(tidyverse)
library(lubridate)
library(psych)


```

This chunk sets up some dummy circadian data (it's from the 'cosinor' function page of 'psych.pdf'):

```{r create-data}


time <- seq(1:24) #create a 24 hour time
pure <- matrix(time,24,18)
colnames(pure) <- paste0("H",1:18)

time <- seq(1:24) #create a 24 hour time
pure <- matrix(time,24,18)
colnames(pure) <- paste0("H",1:18)
#18 different phases but scaled to 0-6 match mood data
pure <- data.frame(time,cos((pure - col(pure))*pi/12)*3 + 3)


```

## Plot the 24 Curves

```{r plot-curves}


matplot(pure[-1],type="l",main="Pure circadian arousal rhythms",
        xlab="time of day",ylab="Arousal")


```

```{r find-acrophase}

#find the acrophases (should match the input)

p <- cosinor(pure) 

p
```

## More plots (the parameters mean ???)

```{r plot-more-plots}

op <- par(mfrow=c(2,2))
cosinor.plot(1,3,pure)
cosinor.plot(1,5,pure)
cosinor.plot(1,8,pure)
cosinor.plot(1,12,pure)

```

```{}
```
